import "./globals.css";
import HeaderTop from "@/components/HeaderTop";
import Hero from "@/components/Hero";
import Patient from "@/components/Patient";
import PatientTestimonals from "@/components/PatientTestimonals";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <HeaderTop/>
        <PatientTestimonals/>
        
        {children}
      </body>
    </html>
  );
}
